task_name: test_task
transform:
   - step: presto.Actuator
     rule: template_rules.Fieldnonempty
     db: qualitis
     target:
       table: rule.qualitis_task_result.mysql
   - step: alarm.Value
     rule: template_rules.Fieldnonempty
     db: qualitis
     exp: '= 0'
     source:
       table: rule.qualitis_task_result.mysql